version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
  build:
    commands:
      - echo Build started on `date`
      - echo Creating index.html file...
      - echo "<!DOCTYPE html><html><head><title>My Website</title></head><body><h1>Hello from CodeBuild!</h1></body></html>" > index.html
      - echo Build completed on `date`
  post_build:
    commands:
      - echo Pushing index.html to S3...
      - aws s3 cp index.html s3://gmailbucket321 --acl public-read
      - echo Deployment completed!

artifacts:
  files:
    - index.html
  discard-paths: no
