version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
  build:
    commands:
      - echo Build started on `date`
      - echo Creating index.html file...
      - echo "<!DOCTYPE html><html><head><title>My Website</title></head><body><h1>Hello from CodePipeline!</h1></body></html>" > index.html
      - echo Build completed on `date`
  post_build:
    commands:
      - echo Pushing index.html to S3...
      - aws s3 cp index.html s3://my-pipeline-bucket-123 --acl public-read

artifacts:
  files:
    - index.html
